### ISSUE TITLE
Upgrade to V15 and merge contributions

### ISSUE THREAD

**Issue by chrisandrewmann** [article714/coreff#2]
Hello,

I would like to connect with the contributors to the Github repository https://github.com/article714/coreff
I work for an Odoo partner in the UK and I’m also a freelance Odoo developer.
Last year we forked your repository and have upgraded it to Odoo V15 as well as made some improvements around CreditSafe functionality.
Thanks for your work and I would like to say it is very impressive.

I’d like to discuss if you would be open to assisting with merging my code into the main branch and starting new branches to support other versions beyond 12.0?
Due to time constraints I am unable to maintain the module entirely on my own so looking to contribute and help where I can in the future.

If you want to take a look at our version, it is here.
https://github.com/Akarigo-Ltd/coreff

Would be good to hear from you with an answer yes or no.
Regards,
Chris

**Comment by xtof-osd** [comment]
Hi @chrisandrewmann , 

sorry for the delay, we have been quite busy lately.

First of all, thanks for your interest in Coreff despite the lack of documentation.
Of course, we will kindly welcome all of your contributions. Please submit a PR and @Kontrolix  will shortly review it and merge-it.

We will also need in a short time-frame to have an odoo 14.0 compatible version of it, so it will be a good occasion to all the enhancements made on 12.0 & 15.0 branches.

So, YES, please submit tour PR and we will take care of reviewing and integrating it to man repo.

Coreff team warmly thanks you for your work.

Regards
Christophe.

**Comment by chrisandrewmann** [comment]
Hello @xtof-osd thanks for the reply.
I'm working to create a PR for both 14.0 and 15.0 branches.
However as there is currently no upstream branch for these, which would you like me to use as the destination branch for the PR? You could always create me a 14.0 and 15.0 branch in preparation based on the current 12.0?

Also i've done a quick test on Odoo 16 and looks like there will need to be a major overhaul as the frontend code has changed significantly (the partner autocomplete widget has been migrated to OWL).
Currently not something i'm expert in so would someone you know be able to contribute to that? It's likely to be needed in the next 3-6 months.

Note: You'll see i've already created 2 PRs, one for 14.0 another for 15.0 going into 12.0 branch.
However if you want me to redo these let me know.

Regards,
Chris

**Comment by xtof-osd** [comment]
Hi @chrisandrewmann ,
all your work has been merged on related branches.
At Tekfor, we will now test the improvement you made, and backport the relevant ones on 12.0 branch.

Regarding the 16.0 port, I don't know either if/when we will be able to contribute on that. We have no knowledge of OWL Yet. 

Again, thanks a lot for the work done 👍 .
Regards,
Christophe.
